/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BookRouteImport } from './routes/book'
import { Route as CancellationPolicyRouteImport } from './routes/cancellation-policy'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AreasIndexRouteImport } from './routes/areas.index'
import { Route as AreasSlugRouteImport } from './routes/areas.$slug'
import { Route as LessonsSlugRouteImport } from './routes/lessons.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const CancellationPolicyRoute = CancellationPolicyRouteImport.update({
  id: '/cancellation-policy',
  path: '/cancellation-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AreasIndexRoute = AreasIndexRouteImport.update({
  id: '/areas/',
  path: '/areas/',
  getParentRoute: () => rootRouteImport,
} as any)
const AreasSlugRoute = AreasSlugRouteImport.update({
  id: '/areas/$slug',
  path: '/areas/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsSlugRoute = LessonsSlugRouteImport.update({
  id: '/lessons/$slug',
  path: '/lessons/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book': typeof BookRoute
  '/cancellation-policy': typeof CancellationPolicyRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reviews': typeof ReviewsRoute
  '/terms': typeof TermsRoute
  '/areas/$slug': typeof AreasSlugRoute
  '/lessons/$slug': typeof LessonsSlugRoute
  '/areas/': typeof AreasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book': typeof BookRoute
  '/cancellation-policy': typeof CancellationPolicyRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reviews': typeof ReviewsRoute
  '/terms': typeof TermsRoute
  '/areas/$slug': typeof AreasSlugRoute
  '/lessons/$slug': typeof LessonsSlugRoute
  '/areas': typeof AreasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book': typeof BookRoute
  '/cancellation-policy': typeof CancellationPolicyRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reviews': typeof ReviewsRoute
  '/terms': typeof TermsRoute
  '/areas/$slug': typeof AreasSlugRoute
  '/lessons/$slug': typeof LessonsSlugRoute
  '/areas/': typeof AreasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/book'
    | '/cancellation-policy'
    | '/contact'
    | '/faq'
    | '/pricing'
    | '/privacy'
    | '/reviews'
    | '/terms'
    | '/areas/$slug'
    | '/lessons/$slug'
    | '/areas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/book'
    | '/cancellation-policy'
    | '/contact'
    | '/faq'
    | '/pricing'
    | '/privacy'
    | '/reviews'
    | '/terms'
    | '/areas/$slug'
    | '/lessons/$slug'
    | '/areas'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/book'
    | '/cancellation-policy'
    | '/contact'
    | '/faq'
    | '/pricing'
    | '/privacy'
    | '/reviews'
    | '/terms'
    | '/areas/$slug'
    | '/lessons/$slug'
    | '/areas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BookRoute: typeof BookRoute
  CancellationPolicyRoute: typeof CancellationPolicyRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ReviewsRoute: typeof ReviewsRoute
  TermsRoute: typeof TermsRoute
  AreasSlugRoute: typeof AreasSlugRoute
  LessonsSlugRoute: typeof LessonsSlugRoute
  AreasIndexRoute: typeof AreasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cancellation-policy': {
      id: '/cancellation-policy'
      path: '/cancellation-policy'
      fullPath: '/cancellation-policy'
      preLoaderRoute: typeof CancellationPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas/': {
      id: '/areas/'
      path: '/areas'
      fullPath: '/areas/'
      preLoaderRoute: typeof AreasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas/$slug': {
      id: '/areas/$slug'
      path: '/areas/$slug'
      fullPath: '/areas/$slug'
      preLoaderRoute: typeof AreasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/$slug': {
      id: '/lessons/$slug'
      path: '/lessons/$slug'
      fullPath: '/lessons/$slug'
      preLoaderRoute: typeof LessonsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BookRoute: BookRoute,
  CancellationPolicyRoute: CancellationPolicyRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ReviewsRoute: ReviewsRoute,
  TermsRoute: TermsRoute,
  AreasSlugRoute: AreasSlugRoute,
  LessonsSlugRoute: LessonsSlugRoute,
  AreasIndexRoute: AreasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
