/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BookRouteImport } from './routes/book'
import { Route as CancellationPolicyRouteImport } from './routes/cancellation-policy'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as MyLessonsRouteImport } from './routes/my-lessons'
import { Route as PassGalleryRouteImport } from './routes/pass-gallery'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AdminBookingsRouteImport } from './routes/admin.bookings'
import { Route as AdminHealthRouteImport } from './routes/admin.health'
import { Route as AreasIndexRouteImport } from './routes/areas.index'
import { Route as AreasSlugRouteImport } from './routes/areas.$slug'
import { Route as BookIndexRouteImport } from './routes/book.index'
import { Route as BookSuccessRouteImport } from './routes/book.success'
import { Route as LessonsSlugRouteImport } from './routes/lessons.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const CancellationPolicyRoute = CancellationPolicyRouteImport.update({
  id: '/cancellation-policy',
  path: '/cancellation-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const MyLessonsRoute = MyLessonsRouteImport.update({
  id: '/my-lessons',
  path: '/my-lessons',
  getParentRoute: () => rootRouteImport,
} as any)
const PassGalleryRoute = PassGalleryRouteImport.update({
  id: '/pass-gallery',
  path: '/pass-gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/admin/bookings',
  path: '/admin/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminHealthRoute = AdminHealthRouteImport.update({
  id: '/admin/health',
  path: '/admin/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AreasIndexRoute = AreasIndexRouteImport.update({
  id: '/areas/',
  path: '/areas/',
  getParentRoute: () => rootRouteImport,
} as any)
const AreasSlugRoute = AreasSlugRouteImport.update({
  id: '/areas/$slug',
  path: '/areas/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BookIndexRoute = BookIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BookRoute,
} as any)
const BookSuccessRoute = BookSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => BookRoute,
} as any)
const LessonsSlugRoute = LessonsSlugRouteImport.update({
  id: '/lessons/$slug',
  path: '/lessons/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book': typeof BookRouteWithChildren
  '/cancellation-policy': typeof CancellationPolicyRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/my-lessons': typeof MyLessonsRoute
  '/pass-gallery': typeof PassGalleryRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reviews': typeof ReviewsRoute
  '/terms': typeof TermsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/health': typeof AdminHealthRoute
  '/areas/$slug': typeof AreasSlugRoute
  '/book/success': typeof BookSuccessRoute
  '/lessons/$slug': typeof LessonsSlugRoute
  '/areas/': typeof AreasIndexRoute
  '/book/': typeof BookIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cancellation-policy': typeof CancellationPolicyRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/my-lessons': typeof MyLessonsRoute
  '/pass-gallery': typeof PassGalleryRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reviews': typeof ReviewsRoute
  '/terms': typeof TermsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/health': typeof AdminHealthRoute
  '/areas/$slug': typeof AreasSlugRoute
  '/book/success': typeof BookSuccessRoute
  '/lessons/$slug': typeof LessonsSlugRoute
  '/areas': typeof AreasIndexRoute
  '/book': typeof BookIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book': typeof BookRouteWithChildren
  '/cancellation-policy': typeof CancellationPolicyRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/my-lessons': typeof MyLessonsRoute
  '/pass-gallery': typeof PassGalleryRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reviews': typeof ReviewsRoute
  '/terms': typeof TermsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/health': typeof AdminHealthRoute
  '/areas/$slug': typeof AreasSlugRoute
  '/book/success': typeof BookSuccessRoute
  '/lessons/$slug': typeof LessonsSlugRoute
  '/areas/': typeof AreasIndexRoute
  '/book/': typeof BookIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/book'
    | '/cancellation-policy'
    | '/contact'
    | '/faq'
    | '/my-lessons'
    | '/pass-gallery'
    | '/pricing'
    | '/privacy'
    | '/reviews'
    | '/terms'
    | '/admin/bookings'
    | '/admin/health'
    | '/areas/$slug'
    | '/book/success'
    | '/lessons/$slug'
    | '/areas/'
    | '/book/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cancellation-policy'
    | '/contact'
    | '/faq'
    | '/my-lessons'
    | '/pass-gallery'
    | '/pricing'
    | '/privacy'
    | '/reviews'
    | '/terms'
    | '/admin/bookings'
    | '/admin/health'
    | '/areas/$slug'
    | '/book/success'
    | '/lessons/$slug'
    | '/areas'
    | '/book'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/book'
    | '/cancellation-policy'
    | '/contact'
    | '/faq'
    | '/my-lessons'
    | '/pass-gallery'
    | '/pricing'
    | '/privacy'
    | '/reviews'
    | '/terms'
    | '/admin/bookings'
    | '/admin/health'
    | '/areas/$slug'
    | '/book/success'
    | '/lessons/$slug'
    | '/areas/'
    | '/book/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BookRoute: typeof BookRouteWithChildren
  CancellationPolicyRoute: typeof CancellationPolicyRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  MyLessonsRoute: typeof MyLessonsRoute
  PassGalleryRoute: typeof PassGalleryRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ReviewsRoute: typeof ReviewsRoute
  TermsRoute: typeof TermsRoute
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminHealthRoute: typeof AdminHealthRoute
  AreasSlugRoute: typeof AreasSlugRoute
  LessonsSlugRoute: typeof LessonsSlugRoute
  AreasIndexRoute: typeof AreasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cancellation-policy': {
      id: '/cancellation-policy'
      path: '/cancellation-policy'
      fullPath: '/cancellation-policy'
      preLoaderRoute: typeof CancellationPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-lessons': {
      id: '/my-lessons'
      path: '/my-lessons'
      fullPath: '/my-lessons'
      preLoaderRoute: typeof MyLessonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pass-gallery': {
      id: '/pass-gallery'
      path: '/pass-gallery'
      fullPath: '/pass-gallery'
      preLoaderRoute: typeof PassGalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/admin/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/health': {
      id: '/admin/health'
      path: '/admin/health'
      fullPath: '/admin/health'
      preLoaderRoute: typeof AdminHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas/': {
      id: '/areas/'
      path: '/areas'
      fullPath: '/areas/'
      preLoaderRoute: typeof AreasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas/$slug': {
      id: '/areas/$slug'
      path: '/areas/$slug'
      fullPath: '/areas/$slug'
      preLoaderRoute: typeof AreasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/': {
      id: '/book/'
      path: '/'
      fullPath: '/book/'
      preLoaderRoute: typeof BookIndexRouteImport
      parentRoute: typeof BookRoute
    }
    '/book/success': {
      id: '/book/success'
      path: '/success'
      fullPath: '/book/success'
      preLoaderRoute: typeof BookSuccessRouteImport
      parentRoute: typeof BookRoute
    }
    '/lessons/$slug': {
      id: '/lessons/$slug'
      path: '/lessons/$slug'
      fullPath: '/lessons/$slug'
      preLoaderRoute: typeof LessonsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BookRouteChildren {
  BookSuccessRoute: typeof BookSuccessRoute
  BookIndexRoute: typeof BookIndexRoute
}

const BookRouteChildren: BookRouteChildren = {
  BookSuccessRoute: BookSuccessRoute,
  BookIndexRoute: BookIndexRoute,
}

const BookRouteWithChildren = BookRoute._addFileChildren(BookRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BookRoute: BookRouteWithChildren,
  CancellationPolicyRoute: CancellationPolicyRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  MyLessonsRoute: MyLessonsRoute,
  PassGalleryRoute: PassGalleryRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ReviewsRoute: ReviewsRoute,
  TermsRoute: TermsRoute,
  AdminBookingsRoute: AdminBookingsRoute,
  AdminHealthRoute: AdminHealthRoute,
  AreasSlugRoute: AreasSlugRoute,
  LessonsSlugRoute: LessonsSlugRoute,
  AreasIndexRoute: AreasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
